---
title: "Analyse Datasets and Models"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r, initialise}

rm(list = ls())

READ_FRESH = FALSE

proj_path   <- file.path(".")
data_path   <- file.path(proj_path, "DataSets")
log_path    <- file.path(proj_path, "Logs")
rdata_path  <- file.path(proj_path, "rData")
config_path <- file.path(proj_path, "config")


data_sets <- list(
  "Baron_Mouse",  # 1,886 cells, 14,861 genes
  "Baron_Human",  # 8,569 cells, 17,499 genes
  "Muraro",       # 2,122 cells, 18,915 genes  
  "SegerStolpe",  # 2,133 cells, 22,757 genes
  "Xin",          # 1,449 cells, 33,889 genes
  "Zhou",         # 2,554 cells, 19,046 genes 
  "Bo",           # 516   cells, 56,924 genes 
  "Petropoulos1"  # 1,529 cells, 26,178 genes 
)

```



```{r, read data}


if (READ_FRESH) {

  gene_names  <- list()
  class_names <- list()
  class_freq  <- list()
  top_genes   <- list()
  
  # Read the data
  
  for (ii in 1:length(data_sets)) {
    dataset_name <- data_sets[[ii]][1]
    cat(sprintf("%s\n", dataset_name))
    
    load(file = file.path(rdata_path, paste0(dataset_name, "_data_and_labels.rData")))
    data   <- data_information[["data"]]
    labels <-data_information[["labels"]]

    gene_names[ii]  <- list(sort(colnames(data)))
    class_names[ii] <- list(sort(str_to_lower(unique(labels[,1]))))
    class_freq[ii]  <- list(table(labels$ident))
    
    load(file = file.path(rdata_path, paste0(dataset_name, "_models.rData")))
    top_genes[ii]      <- list(model_information[["top_genes"]])
  }
  
  names(class_names) <- data_sets
  names(class_freq)  <- data_sets
  names(gene_names)  <- data_sets
 
  # Save the genes per dataset
  save(gene_names, class_names, class_freq, top_genes, file=file.path(rdata_path, "dataset_info.rData"))
  
} else {
  load(file.path(rdata_path, "dataset_info.rData"))
}
```


# Report on datasets
```{r}
for (i in 1:length(gene_names)) {
  cat(sprintf("Corrected length of %20s is %d\n", names(gene_names[i]), length(gene_names[[i]])))
}
```

```{r, class overview}

# Get a list of all class names
all_class = class_names[[1]]
for (c in class_names[-1]) {
  all_class = union(all_class, unlist(c))
}
nr_classes <- length(all_class)

# Create an empty dataframe with as rows the classes and as columns the data zsets
new_col        <- rep(0, nr_classes)
class_overview <- data.frame(start = new_col)

for (c in data_sets) {
  class_overview[c] <- new_col 
}
row.names(class_overview) = all_class
class_overview <- class_overview[,-1]

# Fill the data frame

for (i in 1:length(class_freq)) {
  col_name <- names(class_freq[i])
  for (j in 1:length(class_freq[[i]])) {
    row_name = str_to_lower(names(class_freq[[i]][j]))
    class_overview[row_name, col_name]  = class_freq[[i]][j]
  }
}
class_overview <- class_overview[order(row.names(class_overview)),] 
head(class_overview, 30)

class_info <- data.frame(
  nCell   = colSums(class_overview),
  nClass  = (dim(class_overview)[1] - colCounts(as.matrix(class_overview), value = 0))
)

class_info
```

# How many genes do the data sets have in common?

```{r, common genes}

# How many genes do the data sets have in common?
shared_genes <- gene_names[[1]]
for (i in 2:length(gene_names)) {
  shared_genes = intersect(shared_genes, unlist(gene_names[[i]]))
}
nr_shared_genes <- length(shared_genes)
nr_shared_genes

```


# How many genes are there in total?

```{r, total genes}

total_genes <- gene_names[[1]]
cat(sprintf("Length of set is %d\n", length(total_genes)))
for (i in 2:length(gene_names)) {
  total_genes = union(total_genes, unlist(unlist(gene_names[[i]])))
  cat(sprintf("After adding %s Length of set is %d\n", names(gene_names[i]), length(total_genes)))
}
nr_total_genes <- length(total_genes)
nr_total_genes

```


# Do the top genes appear in all data sets?

```{r, intersect top genes}
size_of_top_genes <- 1000

cat(sprintf("How many of the %d top genes occur in other datasets? \n\n", size_of_top_genes))

for (i in 1:(length(data_sets))) { 
  for (j in (1):length(data_sets)) {
    overlap <- length(intersect(top_genes[[i]][1:size_of_top_genes],
                                gene_names[[j]]))
    cat(sprintf("Of the top %d genes of %-12s %4d occur in the full %-12s dataset\n", size_of_top_genes, data_sets[i], overlap, data_sets[j]))
  }
  cat(sprintf("\n"))
}
```


# Are the top_genes very different in the various datasets?

```{r, topgenes in datasets}
size_of_top_genes <- 1000

cat(sprintf("Analysis of occurance of the top %d genes used in the model in the various data sets.\n\n", size_of_top_genes))

for (i in 1:length(data_sets)) {
  for (j in 1:length(data_sets)) {
    overlap <- length(intersect(top_genes[[i]][1:size_of_top_genes],
                                top_genes[[j]][1:size_of_top_genes]))
    cat(sprintf("The overlap of the %d top genes in model %-12s with the top genes in dataset %-12s is %d\n", 
                size_of_top_genes, data_sets[i], data_sets[j], overlap))
  }
  cat("\n")
}


cat(sprintf("Analysis of occurance of the top %d genes used in the model in the pancreas data sets.\n\n", size_of_top_genes))

for (i in 1:5) { 
  for (j in 1:5) {
    overlap <- length(intersect(top_genes[[i]][1:size_of_top_genes],
                                top_genes[[j]][1:size_of_top_genes]))
    cat(sprintf("The overlap of the %d top genes in model %-12s with the top genes in dataset %-12s is %d\n", 
                size_of_top_genes, data_sets[i], data_sets[j], overlap))
  }
  cat("\n")
}

cat(sprintf("Analysis of occurance of the top %d genes used in the model in the embryonic data sets.\n\n", size_of_top_genes))

for (i in 6:8) { 
  for (j in 6:8) {
    overlap <- length(intersect(top_genes[[i]][1:size_of_top_genes],
                                top_genes[[j]][1:size_of_top_genes]))
    cat(sprintf("The overlap of the %d top genes in model %-12s with the top genes in dataset %-12s is %d\n", 
                size_of_top_genes, data_sets[i], data_sets[j], overlap))
  }
  cat("\n")
}
```
