---
title: "Review AMB data set"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include = FALSE} 
knitr::opts_chunk$set(echo = TRUE)
```


```{r, libraries, message=FALSE}

rm(list = ls())

library(readr)
library(tibble)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(Seurat)
library(caret)
library(data.table)
library(matrixStats)
library(tictoc)
library(MazamaCoreUtils)        # Used for logging messages to a file
library(ggraph)
library(data.tree)
library(DiagrammeR)

```


```{r, initialise, message=FALSE}

PCA_Threshold   <- 0.90         # The percentage variance explained by the PCA
                                # A high percentage requires more PC dimensions to be considered

features_limit  <- 1000         # The number of features that will be considered duringthe PCA
                                # A high number use sthe richness of the data set optimally, but makes processing slo

VERBOSE         <- TRUE         # If TRUE generates analysis data
SEURAT_VERBOSE  <- FALSE
LOGGER          <- FALSE

TRAIN_SVML      <- FALSE
TRAIN_GBM       <- TRUE
TRAIN_GLMNET    <- FALSE

# Summary results will be kept here 
report_out <- data.frame(Method     = character(),
                         ModelData  = character(),
                         TestData   = character(),
                         Accuracy   = numeric(),
                         Confidence = numeric())

# Information of all the runs will be gathered in the class_summaries list  
class_summaries <- list()

proj_path        <- file.path(".")
data_path        <- file.path(proj_path, "DataSets")
log_path         <- file.path(proj_path, "Logs")
rdata_path       <- file.path(proj_path, "rData")
config_path      <- file.path(proj_path, "config")

dataset_name     <- "AMB"
dataset_filename <- paste0(dataset_name, "_ambxxxx")

logger.setup (infoLog = file.path(log_path, "amb.log"))

amb_list         <- list()
```


```{r}

# Get previously stored data back

load(file.path(rdata_path, "amb_list.Rdata"))

```


# Read in the data

```{r, Read}

# Start timer
logger.info("Info: Started reading data from dataset %s", dataset_name)
tic(msg = "", quiet = TRUE)

dataset_name     <- "AMB"
dataset_filename <- paste0(dataset_name, "_hierarchical")

READ_FRESH <- FALSE

if (READ_FRESH) {
  # Read the data and labels and format names
  data      <- read.csv(file.path(data_path, dataset_name, "Data.csv"), 
                        stringsAsFactors = FALSE, 
                        row.names = 1)
  labels    <- read.csv(file.path(data_path, dataset_name, "Labels.csv"), 
                        stringsAsFactors = FALSE)
  
  save(data, labels, file = file.path(rdata_path, "amb_data.rData"))
} else {
  load(file.path(rdata_path, "amb_data.rData"))
}

# Make sure there are no blanks or dashes or slashes in class names
labels      <- apply(labels, 2, function(x) str_replace_all( x, "[ -/]", "."))
labels      <- as.data.frame(labels)
save_data   <- data
save_labels <- labels

# Report timer
toc(log=TRUE, quiet = TRUE)
logger.info("Info: Finished reading data from dataset %s%s", dataset_name, tic.log()[[1]])
tic.clearlog()

```


# Find the Variable Genes 

```{r, variable_features, fig.height=5, message = FALSE, echo=FALSE}

# Start timer
logger.info("Info: Started determining variable genes" )
tic(msg = "", quiet = TRUE)

seurat_object <- CreateSeuratObject(counts    = t(data),
                                    meta.data = as.data.frame(labels),
                                    min.cells = 5)

seurat_object <- NormalizeData(seurat_object, 
                               normalization.method = "LogNormalize", 
                               scale.factor = 1000000)

seurat_object <- FindVariableFeatures(object           = seurat_object, 
                                      selection.method = 'vst',
                                      verbose          = TRUE,
                                      nfeatures        = dim(data)[2])

# Identify the most highly variable genes
top_genes     <- VariableFeatures(seurat_object)

# Show composition
cat(sprintf("Information on dataset after variable gene determination of dataset %s\n", dataset_name))
cat(sprintf("Removed %d genes that apparently are not very variable \n\n", dim(data)[2] - length(top_genes) )) 

data = data[ , top_genes]
cat(sprintf("\nThere are %d cells and %d features.\n", dim(data)[1], dim(data)[2]))

# Report timer
toc(log = TRUE, quiet = TRUE)
logger.info("Info: Ended determining variable genes%s", tic.log()[[1]])
tic.clearlog()

```


```{r, Class information, fig.height=5, message = FALSE, echo=FALSE}

# Start timer
logger.info("Info: Started classinfo")
tic(msg = "", quiet = TRUE)

cat(sprintf("\nClass information for 'Class'\n"))
for (i in 1:length(table(labels$Class))) {
  cat(sprintf("%-25s %d\n", names(table(labels$Class)[i]), table(labels$Class)[i]))
}
cat(sprintf("\n"))

cat(sprintf("\nClass information for 'Subclass'\n"))
for (i in 1:length(table(labels$Subclass))) {
  cat(sprintf("%-25s %d\n", names(table(labels$Subclass)[i]), table(labels$Subclass)[i]))
}
cat(sprintf("\n"))

cat(sprintf("\nClass information for 'cluster'\n"))
for (i in 1:length(table(labels$cluster))) {
  cat(sprintf("%-25s %d\n", names(table(labels$cluster)[i]), table(labels$cluster)[i]))
}
cat(sprintf("\n"))
    
# Plot variable features with and without labels
p1 <- VariableFeaturePlot(seurat_object)
p2 <- LabelPoints(plot   = p1, 
                  points = top_genes[1:15], 
                  repel  = TRUE)
grid.arrange(p1, p2, nrow = 1)
rm(p1, p2)

# Report timer
toc(log = TRUE, quiet = TRUE)
logger.info("Info: Ended classinfo%s", tic.log()[[1]])
tic.clearlog()

```


# Train class level model

```{r, Class Selection}

set.seed(1234)

# Start timer
logger.info("Info: Started Class level")
tic(msg = "", quiet = TRUE)

classification_category <- "Class"
source("Code/Train/process_gbm_model_on_amb_data.R")

model_info = list(
  p1            = p1,
  p2            = p2,
  cm            = cm,
  predicted     = Predicted,
  class_summary = class_summary,
  preproc_model = preproc_model,      
  model_gbm     = model_gbm
)
amb_list[["AMB"]] = model_info

# Report timer
toc(log = TRUE, quiet = TRUE)
logger.info("Info: Ended Class level%s", tic.log()[[1]])
tic.clearlog()

```



# Run the class level model and split up in classes

Use the model to classify the available data. For now we use the full available data

```{r}
data                 <- save_data
labels               <- save_labels

pp_data              <- predict(amb_list[["class"]][["preproc_model"]], data)
predicted_classes    <- predict(amb_list[["class"]][["model_gbm"]], pp_data)

ll <- labels
ll <- cbind(ll, predicted_classes)

table(predicted_classes)

gabaergic_data       <- data[which(predicted_classes   == "GABAergic"),]
gabaergic_labels     <- labels[which(predicted_classes == "GABAergic"),]

glutamatergic_data   <- data[which(predicted_classes   == "Glutamatergic"),]
glutamatergic_labels <- labels[which(predicted_classes == "Glutamatergic"),]

class_models_to_train <- c("GABAergic", "Glutamatergic")

data_to_be_used <- list(
    "GABAergic"     = gabaergic_data,
    "Glutamatergic" = glutamatergic_data
    )

labels_to_be_used <- list(
    "GABAergic"     = gabaergic_labels,
    "Glutamatergic" = glutamatergic_labels
    )
```


#  Train two models to get subclasses for GABAergic and Glutamatergic

```{r, Subclass Selection}

set.seed(1234)

for (m in class_models_to_train) {
  # Start timer
  log_string <- sprintf("Info: Started training %s Subclass levels", m)
  logger.info(log_string)
  tic(msg = "", quiet = TRUE)
  
  classification_category          <- "Subclass"
  data                             <- data_to_be_used[[m]]
  labels                           <- labels_to_be_used[[m]]
  
  source("Code/Train/process_gbm_model_on_amb_data.R")
  
  model_info <- list(
    p1            = p1,
    p2            = p2,
    cm            = cm,
    predicted     = Predicted,
    class_summary = class_summary,
    preproc_model = preproc_model,      
    model_gbm     = model_gbm
  )
  amb_list[[m]] <- model_info
    
  ll <- labels
  ll <- cbind(ll, predicted_classes)
  
  grid.arrange(p1, p2, ncol=2, top = m)
  
  toc(log = TRUE, quiet = TRUE)
  logger.info("Info: Ended training %s subclass levels%s", m, tic.log()[[1]])
  tic.clearlog()
}
```



# Predict subclasses for GABAergic

```{r}

data                 <- gabaergic_data
labels               <- gabaergic_labels

pp_data              <- predict(amb_list[["GABAergic"]][["preproc_model"]], data)
predicted_classes    <- predict(amb_list[["GABAergic"]][["model_gbm"]], pp_data)

ll <- labels
ll <- cbind(ll, predicted_classes)

table(predicted_classes)

pvalb_data       <- data[which(predicted_classes   == "Pvalb"),]
pvalb_labels     <- labels[which(predicted_classes == "Pvalb"),]

lamp5_data       <- data[which(predicted_classes   == "Lamp5"),]
lamp5_labels     <- labels[which(predicted_classes == "Lamp5"),]

sncg_data        <- data[which(predicted_classes   == "Sncg"),]
sncg_labels      <- labels[which(predicted_classes == "Sncg"),]

sst_data         <- data[which(predicted_classes   == "Sst"),]
sst_labels       <- labels[which(predicted_classes == "Sst"),]

serpinf1_data    <- data[which(predicted_classes   == "Serpinf1"),]
serpinf1_labels  <- labels[which(predicted_classes == "Serpinf1"),]

meis2_data      <- data[which(predicted_classes    == "Meis2"),]
meis2_labels    <- labels[which(predicted_classes  == "Meis2"),]

vip_data        <- data[which(predicted_classes    == "Vip"),]
vip_labels      <- labels[which(predicted_classes  == "Vip"),]


gabaergic_subclass_list <- c(
  "Pvalb",
  "Lamp5",
  "Sncg",
  "Sst",
  #"Serpinf1",
  #"Meis2",
  "Vip"
  )

gabaergic_data_list <- list(
  "Pvalb"    = pvalb_data,
  "Lamp5"    = lamp5_data,
  "Sncg"     = sncg_data,
  "Sst"      = sst_data,
  "Serpinf1" = serpinf1_data,
  "Meis2"    = meis2_data,
  "Vip"      = vip_data
  )

gabaergic_labels_list <- list(
  "Pvalb"    = pvalb_labels,
  "Lamp5"    = lamp5_labels,
  "Sncg"     = sncg_labels,
  "Sst"      = sst_labels,
  "Serpinf1" = serpinf1_labels,
  "Meis2"    = meis2_labels,
  "Vip"      = vip_labels
  )

for (m in gabaergic_subclass_list) {
  
  set.seed(1234)
  
  # Start timer
  logger.info("Info: Started training %s cluster level, m")
  tic(msg = "", quiet = TRUE)
  
  classification_category  <- "cluster"
  data                     <- gabaergic_data_list[[m]]
  labels                   <- gabaergic_labels_list[[m]]
  source("Code/Train/process_gbm_model_on_amb_data.R")
  
  model_info = list(
    p1            = p1,
    p2            = p2,
    cm            = cm,
    predicted     = Predicted,
    class_summary = class_summary,
    preproc_model = preproc_model,      
    model_gbm     = model_gbm
  )
  amb_list[[m]] = model_info
  
  ll <- labels
  ll <- cbind(ll, predicted_classes)
  
  grid.arrange(p1, p2, ncol=2, top = m)
  
  # Report timer
  toc(log = TRUE, quiet = TRUE)
  logger.info("Info: Ended training %s cluster %s", m, tic.log()[[1]])
  tic.clearlog()
}

```

@@@@

# Predict subclasses for Glutamatergic

```{r}

data                 <- glutamatergic_data
labels               <- glutamatergic_labels

pp_data              <- predict(amb_list[["Glutamatergic"]][["preproc_model"]], data)
predicted_classes    <- predict(amb_list[["Glutamatergic"]][["model_gbm"]], pp_data)

ll <- labels
ll <- cbind(ll, predicted_classes)

table(predicted_classes)

cr_data      <- data[which(predicted_classes   == "CR"),]
cr_labels    <- labels[which(predicted_classes == "CR"),]

l23it_data   <- data[which(predicted_classes   == "L2.3.IT"),]
l23it_labels <- labels[which(predicted_classes == "L2.3.IT"),]

l4_data      <- data[which(predicted_classes   == "L4"),]
l4_labels    <- labels[which(predicted_classes == "L4"),]

l5it_data    <- data[which(predicted_classes   == "L5.IT"),]
l5it_labels  <- labels[which(predicted_classes == "L5.IT"),]

l5pt_data    <- data[which(predicted_classes   == "L5.PT"),]
l5pt_labels  <- labels[which(predicted_classes == "L5.PT"),]

l6ct_data    <- data[which(predicted_classes    == "L6.CT"),]
l6ct_labels  <- labels[which(predicted_classes  == "L6.CT"),]

l6it_data    <- data[which(predicted_classes    == "L6.IT"),]
l6it_labels  <- labels[which(predicted_classes  == "L6.IT"),]

l6b_data     <- data[which(predicted_classes    == "L6b"),]
l6b_labels   <- labels[which(predicted_classes  == "L6b"),]

np_data      <- data[which(predicted_classes    == "NP"),]
np_labels    <- labels[which(predicted_classes  == "NP"),]

glutamatergic_subclass_list <- c(
  #"CR",      # problem, cause not known 
  "L2.3.IT",
  #"L4",      # do nor try this because it has only one class, no model needed
  "L5.IT",
  "L5.PT",
  "L6.CT",
  "L6.IT",
  "L6b",
  "NP"
  )

glutamatergic_data_list <- list(
  "CR"      = cr_data,
  "L2.3.IT" = l23it_data,
  "L4"      = l4_data,
  "L5.IT"   = l5it_data,
  "L5.PT"   = l5pt_data,
  "L6.CT"   = l6ct_data,
  "L6.IT"   = l6it_data,
  "L6b"     = l6b_data,
  "NP"      = np_data
  )

glutamatergic_labels_list <- list(
  "CR"      = cr_labels,
  "L2.3.IT" = l23it_labels,
  "L4"      = l4_labels,
  "L5.IT"   = l5it_labels,
  "L5.PT"   = l5pt_labels,
  "L6.CT"   = l6ct_labels,
  "L6.IT"   = l6it_labels,
  "L6b"     = l6b_labels,
  "NP"      = np_labels
  )

for (m in glutamatergic_subclass_list) {
  
  set.seed(1234)
  
  # Start timer
  logger.info("Info: Started training %s cluster level, m")
  tic(msg = "", quiet = TRUE)
  
  classification_category  <- "cluster"
  data                     <- glutamatergic_data_list[[m]]
  labels                   <- glutamatergic_labels_list[[m]]
  source("Code/Train/process_gbm_model_on_amb_data.R")
  
  model_info = list(
    p1            = p1,
    p2            = p2,
    cm            = cm,
    predicted     = Predicted,
    class_summary = class_summary,
    preproc_model = preproc_model,      
    model_gbm     = model_gbm
  )
  amb_list[[m]] = model_info
  
  ll <- labels
  ll <- cbind(ll, predicted_classes)
  
  grid.arrange(p1, p2, ncol=2, top = m)
  
  # Report timer
  toc(log = TRUE, quiet = TRUE)
  logger.info("Info: Ended training %s cluster %s", m, tic.log()[[1]])
  tic.clearlog()
}

```





```{r}
save(amb_list, file = file.path(rdata_path, "amb_list.Rdata"))
```






