---
title: "Compile Data"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

rm(list = ls())    # Remove all variables
cat("\014")        # Clear the console
set.seed(1234)     # For random repeatability

```

# Initialise

```{r, libraries, message=FALSE}

rm(list = ls())

library(readr)
library(tibble)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(gridExtra)

library(data.table)
library(matrixStats)

source("Code/utilities.R")

```


```{r, general initialise, message=FALSE}

report_table    <- data.frame()

# Paths
proj_path       <- file.path(".")
data_path       <- file.path(proj_path, "DataSets")
log_path        <- file.path(proj_path, "Logs")
rdata_path      <- file.path(proj_path, "rData")
config_path     <- file.path(proj_path, "config")


```


```{r}
report_table     <- data.frame()
files_to_process <- list.files(file.path(rdata_path, "ReportData"))
print(files_to_process)
cat("\n\n")

for (file in files_to_process)  {
  print(file)
  load (file.path(rdata_path, "ReportData", file))
  report_table <- rbind(report_table, report_out)
}

```

## Generate the results table 


## pca

```{r}
medianF1_pca_table    <- data.frame()
duration_pca_table    <- data.frame()

rt <- report_table %>% filter(PreProc == "pca")

for (i in 1:dim(rt)[1]) {
  row                          <- as.character(rt[i, "Method"])
  col                          <- as.character(rt[i, "ModelName"])
  medianF1                     <- round( rt[i, "MedianF1"],2)
  medianF1_pca_table[row, col] <- medianF1
  duration                     <- round( rt[i, "duration"],0)
  duration_pca_table[row, col] <- duration
}

medianF1_pca_table["svmLinear", "Nr"] <- 1
medianF1_pca_table["svmRadial", "Nr"] <- 2
medianF1_pca_table["rf", "Nr"]        <- 3
medianF1_pca_table["gbm", "Nr"]       <- 4

medianF1_pca_table %>% 
  rownames_to_column(var = "rowname") %>%
  select("Xin", "Muraro", "Baron_Human", "Baron_Mouse", "SegerStolpe", "Zhou", "Bo", "Petropoulos1", "Nr", "rowname") %>%
  arrange(Nr) %>%
  column_to_rownames(var = "rowname") %>%
  select(-Nr)
```


```{r}
duration_pca_table["svmLinear", "Nr"] <- 1
duration_pca_table["svmRadial", "Nr"] <- 2
duration_pca_table["rf", "Nr"]        <- 3
duration_pca_table["gbm", "Nr"]       <- 4

duration_pca_table %>% 
  rownames_to_column(var = "rowname") %>%
  select("Xin", "Muraro", "Baron_Human", "Baron_Mouse", "SegerStolpe", "Zhou", "Bo", "Petropoulos1", "Nr", "rowname") %>%
  arrange(Nr) %>%
  column_to_rownames(var = "rowname") %>%
  select(-Nr)
  

```


## nopca

```{r}
medianF1_nopca_table  <- data.frame()
duration_nopca_table  <- data.frame()

rt <- report_table %>% filter(PreProc == "nopca")

for (i in 1:dim(rt)[1]) {
  row                            <- as.character(rt[i, "Method"])
  col                            <- as.character(rt[i, "ModelName"])
  medianF1                       <- round( rt[i, "MedianF1"],2)
  medianF1_nopca_table[row, col] <- medianF1
  duration                       <- round( rt[i, "duration"],0)
  duration_nopca_table[row, col] <- duration
}

medianF1_nopca_table["svmLinear", "Nr"] <- 1
medianF1_nopca_table["svmRadial", "Nr"] <- 2
medianF1_nopca_table["rf", "Nr"]        <- 3
medianF1_nopca_table["gbm", "Nr"]       <- 4

medianF1_nopca_table %>% 
  rownames_to_column(var = "rowname") %>%
  select("Xin", "Muraro", "Baron_Human", "Baron_Mouse", "SegerStolpe", "Zhou", "Bo", "Petropoulos1", "Nr", "rowname") %>%
  arrange(Nr) %>%
  column_to_rownames(var = "rowname") %>%
  select(-Nr)
```


```{r}
duration_nopca_table["svmLinear", "Nr"] <- 1
duration_nopca_table["svmRadial", "Nr"] <- 2
duration_nopca_table["rf", "Nr"]        <- 3
duration_nopca_table["gbm", "Nr"]       <- 4

duration_nopca_table %>% 
  rownames_to_column(var = "rowname") %>%
  select("Xin", "Muraro", "Baron_Human", "Baron_Mouse", "SegerStolpe", "Zhou", "Bo", "Petropoulos1", "Nr", "rowname") %>%
  arrange(Nr) %>%
  column_to_rownames(var = "rowname") %>%
  select(-Nr)

```


## logpca

```{r}
medianF1_logpca_table <- data.frame()
duration_logpca_table <- data.frame()

rt <- report_table %>% filter(PreProc == "logpca")

for (i in 1:dim(rt)[1]) {
  row                             <- as.character(rt[i, "Method"])
  col                             <- as.character(rt[i, "ModelName"])
  medianF1                        <- round( rt[i, "MedianF1"],2)
  medianF1_logpca_table[row, col] <- medianF1
  duration                        <- round( rt[i, "duration"],0)
  duration_logpca_table[row, col] <- duration
}

medianF1_logpca_table["svmLinear", "Nr"] <- 1
medianF1_logpca_table["svmRadial", "Nr"] <- 2
medianF1_logpca_table["rf", "Nr"]        <- 3
medianF1_logpca_table["gbm", "Nr"]       <- 4

medianF1_logpca_table %>% 
  rownames_to_column(var = "rowname") %>%
  select("Xin", "Muraro", "Baron_Human", "Baron_Mouse", "SegerStolpe", "Zhou", "Bo", "Petropoulos1", "Nr", "rowname") %>%
  arrange(Nr) %>%
  column_to_rownames(var = "rowname") %>%
  select(-Nr)
```


```{r}
duration_logpca_table["svmLinear", "Nr"] <- 1
duration_logpca_table["svmRadial", "Nr"] <- 2
duration_logpca_table["rf", "Nr"]        <- 3
duration_logpca_table["gbm", "Nr"]       <- 4

duration_logpca_table %>% 
  rownames_to_column(var = "rowname") %>%
  select("Xin", "Muraro", "Baron_Human", "Baron_Mouse", "SegerStolpe", "Zhou", "Bo", "Petropoulos1", "Nr", "rowname") %>%
  arrange(Nr) %>%
  column_to_rownames(var = "rowname") %>%
  select(-Nr)

```




```{r}

colr <- RColorBrewer::brewer.pal(9, "GnBu")


cpd <- report_table %>%
  mutate (PreProc  = as.character(PreProc)) %>%
  mutate (PreProc  = replace(PreProc, PreProc == "nopca" , "No PCA")) %>%
  mutate (PreProc  = replace(PreProc, PreProc == "pca" ,    "Just PCA")) %>%  
  mutate (PreProc  = replace(PreProc, PreProc == "logpca", "Log and PCA"))

cpd$Method    <- factor(cpd$Method, levels=c("svmLinear", "svmRadial", "rf", "gbm"))
cpd$ModelName <- factor(cpd$ModelName, levels=c("Xin", "Muraro" , "Baron_Human",  "Baron_Mouse", "SegerStolpe", "Zhou",  "Bo", "Petropoulos1"))
    
ggplot(cpd, aes(x = Method, y = MedianF1, fill = as.factor(Method))) +
  geom_bar(stat= "identity", width = 0.3) +
  facet_grid (vars(ModelName), vars(PreProc)) +
  scale_fill_manual(values = c(colr[2], colr[4], colr[6], colr[7]) ) +
  ylim(0, 1) +
  ylab("Median F1") +
  theme_light() +
  theme(legend.title=element_blank()) 


```


```{r, fig.width = 5}
plot_data <- report_table %>%
  filter(PreProc == "pca")

ggplot(plot_data) +
  geom_point(aes(x = MedianF1, y = confidence, col = ModelName)) +
  xlab("Median F1") +
  facet_wrap( ~ Method) +
  scale_x_continuous(limits = c(0, 1)) +
  scale_y_continuous(limits = c(0, 1)) +
  theme_light()
```


```{r, fig.width = 5}

plot_data <- report_table %>%
  filter(PreProc == "pca")

ggplot(plot_data) +
  geom_point(aes(x = MedianF1, y = confidence, col = Method)) +
  xlab("Median F1") +
  scale_x_continuous(limits = c(0, 1)) +
  scale_y_continuous(limits = c(0, 1)) +
  facet_wrap( ~ ModelName) +
  theme_light()

```
```


