---
title: "Generate Datasets"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include = FALSE} 
knitr::opts_chunk$set(echo = TRUE)
```


# Initialise

```{r, libraries, message=FALSE}

rm(list = ls())

library(readr)
library(tibble)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(Seurat)
library(caret)
library(data.table)
library(matrixStats)
library(tictoc)                 # Used for timing of code
library(MazamaCoreUtils)        # Used for logging messages to a file

source("Code/process_config.R")
source("Code/utilities.R")

proj_path   <- file.path(".")
data_path   <- file.path(proj_path, "DataSets")
log_path    <- file.path(proj_path, "Logs")
rdata_path  <- file.path(proj_path, "rData")
config_path <- file.path(proj_path, "config")

```



# Read, process and save


```{r, fig.width = 5}

generate_dataset <- function (data_path, dataset_name) {
  
  print(dataset_name)
  
  # Set the data and model name and read the data
  ret            <- read_csv_dataset(data_path, dataset_name)
  data           <- ret$data
  labels         <- ret$labels
  
  # Read the configuration file and process data 
  ret            <- read_config(config_path  = config_path,
                                     dataset_name = dataset_name)
  config_data    <- ret$config_data
    
  min_class_size <- config_data["min_class_size", "Value"]
  minCount       <- config_data["minCount", "Value"] 
  maxCount       <- config_data["maxCount", "Value"]
  minFeature     <- config_data["minFeature", "Value"] 
  maxFeature     <- config_data["maxFeature", "Value"] 


  ########################################
  # Overrule settings from config file
  ########################################

  min_class_size      <- 10 
  minCount            <- 0 
  maxCount            <- -1
  minFeature          <- 0 
  maxFeature          <- -1   

  ret                 <- process_config(min_class_size, minCount, maxCount, minFeature, maxFeature, data, labels)
  data                <- ret$data
  labels              <- ret$labels
  
  save_single_data (rdata_path, dataset_name, data, labels) 
}

```


```{r}
generate_dataset(data_path, "Xin")
```


```{r}
generate_dataset(data_path, "Muraro")
```


```{r}
generate_dataset(data_path, "Baron_Human")
```


```{r}
generate_dataset(data_path, "Baron_Mouse")
```


```{r}
generate_dataset(data_path, "SegerStolpe")
```


```{r}
generate_dataset(data_path, "Zhou")
```


```{r}
generate_dataset(data_path, "Bo")
```


```{r}
generate_dataset(data_path, "Petropoulos1")
```


