---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())

library(plyr) 
library(data.table)
library(tidyverse)

```


```{r}
proj_path   <- file.path(".")
data_path   <- file.path(proj_path, "DataSets")
log_path    <- file.path(proj_path, "Logs")
rdata_path  <- file.path(proj_path, "rData")
config_path <- file.path(proj_path, "config")   
import_path <- file.path(proj_path, "../Import_Data") 
```


 

# Process Bo data

## The count table

```{r}

data_bo             <- as.data.frame(fread("../Import_Data/Bo/GSE125616_READ_COUNT_table_lvbo_TE_gencode.txt", 
                                           header = TRUE))
data_bo             <- data_bo[,-c(2:6)]
data_bo             <- column_to_rownames(data_bo, var = "Geneid")
data_bo             <- t(data_bo)
data_bo             <- as.data.frame(data_bo)
dim(data_bo)

```

## The labels

```{r}

labels_bo              <- as.data.frame(fread("../Import_Data/Bo/cell.lineage.csv", header = TRUE))

labels_bo              <- labels_bo[, c("Phase", "V1")]
labels_bo              <- as.data.frame(apply(as.matrix(labels_bo), 2, function(x) str_replace(x, "Untypical", "na")))
labels_bo              <- column_to_rownames(labels_bo, var = "V1")
labels_bo[,"cell_id"]  <- rownames(labels_bo)
colnames(labels_bo)[1] <- "ident"
dim(labels_bo)

```


```{r}

data_bo   <- data_bo[intersect(rownames(data_bo),   rownames(labels_bo)), ]
labels_bo <- labels_bo[intersect(rownames(data_bo), rownames(labels_bo)), ]
dim(labels_bo)
dim(data_bo)

```


```{r}

write.csv(labels_bo[ ,1], "DataSets/Bo/labels.csv", row.names = FALSE)
write.csv(data_bo,        "DataSets/Bo/data.csv",   row.names = TRUE)

```



# Process Zhou data

## The count table

```{r}

data_zhou  <- as.data.frame(fread("../Import_Data/Zhou/GSE109555_TrioSeq_TPM.txt", header = FALSE))
data_zhou  <- column_to_rownames(data_zhou, var = "V1")
data_zhou  <- t(data_zhou)
dim(data_zhou)

```


## The labels

```{r}

labels_zhou              <- as.data.frame(fread("../Import_Data/Zhou/GSE109555_TrioSeq_DataInfo.txt",header = FALSE))
labels_zhou              <- column_to_rownames(labels_zhou, var = "V1")
labels_zhou[,"V11"]      <- apply(as.matrix(labels_zhou[,"V11"]), 2, function(x) str_replace(x, "Epi", "EPI"))
labels_zhou              <- labels_zhou[ , c("V11", "V2")]
colnames(labels_zhou)    <- c("ident", "cell_id")
dim(labels_bo)

```


```{r}

rownames(data_zhou) <- rownames(labels_zhou)

```


```{r}

write.csv(labels_zhou[ ,1], "DataSets/Zhou/labels.csv", row.names = FALSE)
write.csv(data_zhou,        "DataSets/Zhou/data.csv",   row.names = TRUE)

```




# Process Petropoulos

## The count table

```{r}

# petr1  <- as.data.frame(fread("../Import_Data/Petropoulos/ercc.counts.txt", header = FALSE))
# petr2  <- as.data.frame(fread("../Import_Data/Petropoulos/ercc.rpkm.txt", header = FALSE))
# petr3  <- as.data.frame(fread("../Import_Data/Petropoulos/rpkm.txt", header = FALSE))
# petr4  <- as.data.frame(fread("../Import_Data/Petropoulos/counts.txt", header = FALSE))
# petr5  <- as.data.frame(fread("../Import_Data/Petropoulos/E-MTAB-3929.sdrf.txt", header = FALSE))

data_petr1  <- as.data.frame(fread("../Import_Data/Petropoulos/counts.txt", header = TRUE))
data_petr1  <- column_to_rownames(data_petr1, var = "V1")
data_petr1  <- as.data.frame(t(data_petr1))

data_petr2  <- as.data.frame(fread("../Import_Data/Petropoulos/rpkm.txt", header = TRUE))
data_petr2  <- column_to_rownames(data_petr2, var = "V1")
data_petr2  <- as.data.frame(t(data_petr2))

```


## The labels

```{r}

labels_petr <- as.data.frame(fread("../Import_Data/Petropoulos/E-MTAB-3929.sdrf.txt", header = TRUE))
labels_petr <- labels_petr[ ,  c("Characteristics[inferred lineage]", "Source Name", "Source Name" )]
labels_petr <- column_to_rownames(labels_petr, var = "Source Name")
colnames(labels_petr) = c("ident", "cell_id")
labels_petr[ , "ident"] <- apply(as.matrix(labels_petr[ , "ident"]), 2, function(x) str_replace(x, "trophectoderm", "TE"))
labels_petr[ , "ident"] <- apply(as.matrix(labels_petr[ , "ident"]), 2, function(x) str_replace(x, "epiblast", "EPI"))
labels_petr[ , "ident"] <- apply(as.matrix(labels_petr[ , "ident"]), 2, function(x) str_replace(x, "primitive endoderm", "PE"))
labels_petr[ , "ident"] <- apply(as.matrix(labels_petr[ , "ident"]), 2, function(x) str_replace(x, "not applicable", "na"))


```


```{r}

rownames(data_petr1) <- rownames(labels_petr)
rownames(data_petr2) <- rownames(labels_petr)

```


```{r}

write.csv(labels_petr[ ,1], "DataSets/Petropoulos1/labels.csv", row.names = FALSE)
write.csv(data_petr1,       "DataSets/Petropoulos1/data.csv",   row.names = TRUE)

write.csv(labels_petr[ ,1], "DataSets/Petropoulos2/labels.csv", row.names = FALSE)
write.csv(data_petr2,       "DataSets/Petropoulos2/data.csv",   row.names = TRUE)

```



