---
title: "Review AMB data set"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include = FALSE} 
knitr::opts_chunk$set(echo = TRUE)
```


```{r, libraries, message=FALSE}

library(readr)
library(tibble)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(Seurat)
library(caret)
library(data.table)
library(matrixStats)
library(tictoc)
library(MazamaCoreUtils)        # Used for logging messages to a file

rm(list = ls())

```


```{r, initialise, message=FALSE}

proj_path        <- file.path(".")
data_path        <- file.path(proj_path, "DataSets")
log_path         <- file.path(proj_path, "Logs")
rdata_path       <- file.path(proj_path, "rData")
config_path      <- file.path(proj_path, "config")

dataset_name     <- "AMB"
dataset_filename <- paste0(dataset_name, "_ambxxxx")

logger.setup (infoLog = file.path(log_path, "amb.log"))

```


# Read in the data


```{r, Read}

labels    <- read.csv(file.path(data_path, dataset_name, "Labels.csv"), 
                      stringsAsFactors = FALSE)
  

# Make sure there are no blanks or dashes or slashes in class names
labels      <- apply(labels, 2, function(x) str_replace_all( x, "[ -/]", "."))
labels      <- as.data.frame(labels)
save_data   <- data
save_labels <- labels

```


```{r}
labels %>%
  group_by(Class) %>%
  summarise(n = n()) %>%
  filter( n > 10) %>%
  arrange (Class)
```


```{r}
labels %>%
  group_by(Subclass) %>%
  summarise(n = n()) %>%
  filter( n > 10) %>%
  arrange (Subclass)
```


```{r}
labels %>%
  group_by(cluster) %>%
  summarise(n = n()) %>%
  filter( n > 10) %>%
  arrange (cluster)
```



```{r}
labels %>%
  group_by(Class, Subclass) %>%
  summarise(n = n())  %>%
  filter( n > 10) %>%
  arrange (Class, Subclass) %>%
  summarise(n = n())  
```



```{r}
labels %>%
  group_by(Class, Subclass, cluster) %>%
  summarise(n = n())  %>%
  filter( n > 10) %>%
  arrange (Class, Subclass, cluster) %>%
  summarise(n = n())
```


```{r}
labels %>%
  group_by(Class, Subclass, cluster) %>%
  summarise(n = n())  %>%
  filter( n > 10) %>%
  arrange (Class, Subclass, cluster) %>%
  summarise(n = n())   %>%
  summarise(n = n())  

```


```{r}
l <- labels
l$amb        <- rep("amb", dim(l)[1])
l            <- l[, c("amb", "Class")]
l$pathString <- do.call(paste,c(l,sep="/"))
l.graph      <- data.tree::as.Node(l)
plot(l.graph)
```


```{r}

l <- labels
l$amb        <- rep("amb", dim(l)[1])
l            <- l[, c("amb", "Class", "Subclass")]
l$pathString <- do.call(paste,c(l,sep="/"))
l.graph      <- data.tree::as.Node(l)
plot(l.graph)

```


```{r}

l <- labels
l <- l %>%
  filter(Class == "Glutamatergic") %>%
  select(Class, Subclass)
l$pathString <- do.call(paste,c(l,sep="/"))
l.graph      <- data.tree::as.Node(l)
plot(l.graph)

```


```{r}

l <- labels
l <- l %>%
  filter(Class == "GABAergic") %>%
  select(Class, Subclass)
l$pathString <- do.call(paste,c(l,sep="/"))
l.graph      <- data.tree::as.Node(l)
plot(l.graph)

```


```{r}

l <- labels
l <- l %>%
  filter(Subclass == "Lamp5") %>%
  select(Subclass, cluster)
l$pathString <- do.call(paste,c(l,sep="/"))
l.graph      <- data.tree::as.Node(l)
plot(l.graph)

```

`

